### ISSUE TITLE
Remove google code 

### ISSUE THREAD

**Issue by derschiw** [plantagoIT/Spina#2]
There is some code we might not want to have
`= javascript_include_tag '//html5shiv.googlecode.com/svn/trunk/html5.js', data: {turbolinks_track: true}`

**Comment by derschiw** [comment]
`views/spina/sitemaps/show.xml.builder`

**Comment by derschiw** [comment]
`views/spina/shared/_google_site_verification.html.haml`

**Comment by derschiw** [comment]
`views/spina/shared/_analytics.html.haml`

**Comment by kahrpatrick** [comment]
> There is some code we might not want to have
> `= javascript_include_tag '//html5shiv.googlecode.com/svn/trunk/html5.js', data: {turbolinks_track: true}`

Removed in upstream master

**Comment by kahrpatrick** [comment]
> `views/spina/sitemaps/show.xml.builder`

Needs to be updated: 
https://developers.google.com/search/docs/advanced/sitemaps/build-sitemap?ref_topic=4581190&visit_id=637546169364285966-640127593&rd=1#expandable-1

**Comment by kahrpatrick** [comment]
> `views/spina/shared/_analytics.html.haml`

Maybe a left-over: 
https://github.com/SpinaCMS/Spina/pull/514
