### ISSUE TITLE
Make active links in navigation

### ISSUE THREAD

**Issue by derschiw** [plantagoIT/Spina#3]
In spina js is used to add a `.active` class to the page the user is currently on. This is now broken without js. Since the controller only renders a partial for the content, the `.active` class is not moved.

**Comment by kahrpatrick** [comment]
I extended the Spina MenuPresenter to add an `.active` class to navigation items.
```
      def get_active_class(item, item_css)
        @current_path == item.materialized_path ? item_css + " " + active_class : item_css
      end 
```
